### ISSUE TITLE
Auto address fill is not working on frontend for dutch

### ISSUE THREAD

**Issue by Tanuja0202** [postcode-nl/PostcodeNl_Api_Magento2#11]
![auto](https://user-images.githubusercontent.com/57166346/76626191-ba96d600-655e-11ea-9cce-eff77494c664.png)
 Magento  version: 2.3.4

**Comment by gerben86** [comment]
Which one-page-checkout are you using?

**Comment by Tanuja0202** [comment]
https://www.onestepcheckout.com/community-m2.html

**Comment by JozefVerhoef** [comment]
@Tanuja0202 we'd like to look into this, can you contact us at tech@postcode.nl?

**Comment by JozefVerhoef** [comment]
@Tanuja0202  I'm closing this because we haven't heard from you. Please contact us if this is still an issue.
