### ISSUE TITLE
Plugin ignores Magento basedir, always loads /rest in js

### ISSUE THREAD

**Issue by SjonHortensius** [postcode-nl/PostcodeNl_Api_Magento2#12]
It seems this plugin should take the Magente basedirectory into account, instead of the current fixed URL  which references `/rest/` directly: https://github.com/postcode-nl/PostcodeNl_Api_Magento2/blob/8f90e7b32b7db62a49d997ce8c79d2f6dcaf5209/view/frontend/templates/customer/address.phtml#L63

This doesn't work when Magento runs from a subdirectory

**Comment by tmishutin** [comment]
Fixed in https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/13
