### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matches' of undefined - postcode_autofill_client.js:908

### ISSUE THREAD

**Issue by hypershopbv** [postcode-nl/PostcodeNl_Api_Magento2#17]
In the customer account area, we get the following error:
Uncaught TypeError: Cannot read property 'matches' of undefined
postcode_autofill_client.js:908

Magento is using 3 address fields.

Please advise.

**Comment by JozefVerhoef** [comment]
Is this still an issue when using release 2.0.3?

**Comment by hypershopbv** [comment]
No, this is working correctly now, thanks!
