### ISSUE TITLE
Compatible with MyParcel?

### ISSUE THREAD

**Issue by gerben86** [postcode-nl/PostcodeNl_Api_Magento2#2]
Is this plugin compatible with the MyParcel plugin / did you test that?: https://github.com/myparcelnl/magento

Because I know that the Hoofdfabriek-poctode-plugin and MyParcel had issues , so I hope that that's not the case with this extension.

**Comment by tmishutin** [comment]
Hi @gerben86 we did not test it with this plugin. If MyParcel is not changing fields in checkout form, it should work fine.

**Comment by gerben86** [comment]
Tnx, we'll give it a try!
