### ISSUE TITLE
Housenumber and addition not set to 2nd and 3rd field

### ISSUE THREAD

**Issue by hypershopbv** [postcode-nl/PostcodeNl_Api_Magento2#20]
Hi,

We have 3 address fields enabled in the Magento backend. However, this setting is ignored by the extension. When i add my address, the housenumber is not copied to the 2nd address field, addition is not copied to 3rd address field. (see screenshot).

Can you enabled support for multiple address fields?

<img width="672" alt="Screenshot 2020-05-12 at 07 59 05" src="https://user-images.githubusercontent.com/24226635/81643730-77ee5e80-9426-11ea-830c-1b2dda24d2a2.png">

**Comment by jvkranenburg** [comment]
Same here, but than we have 2 fields. One for street name and one for housenumber.
How to split the final address over multiple fields?

**Comment by JozefVerhoef** [comment]
This has been fixed in the latest release
