### ISSUE TITLE
Please don't update the version number when no database changes have been done

### ISSUE THREAD

**Issue by peterjaap** [postcode-nl/PostcodeNl_Api_Magento2#33]
In the 3.1.1 release, the database scheme has a version upgrade; https://github.com/postcode-nl/PostcodeNl_Api_Magento2/compare/3.1.0...3.1.1

But the code only contains Javascript changes. Please refrain from updating the database scheme version - this causes downtime for us since Magento thinks it needs to do a database update and goes into maintenance mode. Without the database scheme version change, we will have zero downtime releases since no database update is needed.

There is no need for the database version scheme to be on par with the extension version itself.

Thanks.

**Comment by JozefVerhoef** [comment]
Thanks for the feedback!
