### ISSUE TITLE
GraphQl integration?

### ISSUE THREAD

**Issue by Hexmage** [postcode-nl/PostcodeNl_Api_Magento2#34]
Are there any plans to have an graphql endpoint for the PostcodeNl api so we can use the module with PWA?

**Comment by marcoboom** [comment]
Is this already on the roadmap?

**Comment by Hexmage** [comment]
In the meantime I made one myself. https://github.com/experius/Mage2-Module-Experius-PostcodeGraphQl

**Comment by marcoboom** [comment]
Thanks @Hexmage
