### ISSUE TITLE
Save inputs to session checkout-data

### ISSUE THREAD

**Issue by Steekvlam** [postcode-nl/PostcodeNl_Api_Magento2#35]
Currently when you fill in all fields and the address has been checked, when you go back to the shopping cart and return to the checkout the postcode check fields are empty and no address is showed.

Solution is to store the postcode values in de checkout-data and check them when available and fill in the fields.

**Comment by JelleGe** [comment]
Any update on this? Seems that this is not solved.

**Comment by JerrySmidt** [comment]
Didn't get this to work. Maybe later.

**Comment by JelleGe** [comment]
@JerrySmidt That's too bad. This does cause some issues in a live environment. Especially when a payment fails and the customer returns in the checkout, for example. Or when a customer returns to any page on the website and then returns to the checkout. Is it that hard to implement?

**Comment by JerrySmidt** [comment]
Agreed, this would be a nice feature to have. There doesn't seem to be much/any documentation on how to implement it, so it may take some time to find out how make this work.

If you have a solution, feel free to contribute of course.

**Comment by JelleGe** [comment]
Is it also not displayed well in the documentation: https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_form.html?

**Comment by JelleGe** [comment]
See also the following topic about it:

https://magento.stackexchange.com/questions/359127/custom-checkout-field-save-input-value-in-session-magento-2-4/359157#359157

**Comment by JelleGe** [comment]
Any update on this?

**Comment by JerrySmidt** [comment]
This functionality has been implemented in 3.3.0.
