### ISSUE TITLE
Make input fields mandatory

### ISSUE THREAD

**Issue by marcoveeneman** [postcode-nl/PostcodeNl_Api_Magento2#36]
Hi,

Is it possible to make the address input fields of this module mandatory to fill in by the customer? Magento currently prevents to go to the next checkout page when the address is not filled in and gives no feedback to the customer about what is missing. Making the postcode/housenumber (nl) or address (intl) field mandatory would help a lot.

**Comment by marcoveeneman** [comment]
Any news about this topic?

**Comment by JerrySmidt** [comment]
Fixed.
