### ISSUE TITLE
No addresses are shown when searching for 50670 in DE

### ISSUE THREAD

**Issue by JSeverein** [postcode-nl/PostcodeNl_Api_Magento2#38]
Hi,

When our customer searches for 50670 for the country DE they get the result 50670 Koln, which is the correct city. But after that there are no streets shown. When they instead search for Klingelpütz 70 their address is found and 50670 and Koln are correctly filled as postcode and city.

Why is it not possible to search based on postcode? because the label does suggest it: Start typing your address or zip/postal code.

**Comment by JozefVerhoef** [comment]
After selecting the '50670 Koln' the customer can simply start typing the street name. This is not a bug.

To prevent such confusion we will be adding a new API feature (expected in January) to suggest a few street names after selecting a postcode and/or city. A module update will not be needed to enable this functionality, it will simply work immediately when available.
