### ISSUE TITLE
support for PHP 8.1

### ISSUE THREAD

**Issue by miyvrey2** [postcode-nl/PostcodeNl_Api_Magento2#48]
Hi,

For one of our customers we are implementing the latest version of Magento (2.4.4) and it seems we cannot update this module because of PHP 8.1 is not yet supported. Is there any sight on when this can be supported?

Kind regards,
Jeffrey

**Comment by JerrySmidt** [comment]
Fixed in release 3.1.5.

**Comment by miyvrey2** [comment]
Hi @JerrySmidt ,

It seems that the composer.json still expects PHP 7.* and not PHP 7.* | 8.*. Could you look into this?

Kind regards,
Jeffrey
