### ISSUE TITLE
Add PHP 8.1 / Magento 2.4.4 compatibility

### ISSUE THREAD

**Issue by peterjaap** [postcode-nl/PostcodeNl_Api_Magento2#49]

**Comment by jorgb90** [comment]
With the latest version still getting:

    - postcode-nl/api-magento2-module is locked to version 3.1.5 and an update of this package was not requested.
    - postcode-nl/api-magento2-module 3.1.5 requires php 7.* -> your php version (8.1.7) does not satisfy that requirement.
