### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by gerben86** [postcode-nl/PostcodeNl_Api_Magento2#5]
It would be a big improvement if there were translations (or at least a i18n dir and files) provided so it's easier to customize the extension and the frontend.
Now everything is in English by default.

**Comment by JozefVerhoef** [comment]
Which texts would you like to be able to translate? 

Any text that is part of the autocomplete drop down comes from the Postcode.nl API response, which is in the language determined by the configured store language.  

For supported API languages, see the language parameter described at https://api.postcode.nl/documentation/international/v1/Autocomplete/autocomplete

**Comment by gerben86** [comment]
I saw at least those 2 on the frontend:
1. Address validation -> Rename to something like:"Adres validatie"
2. Fill out your postcode and housenumber to auto-complete your address. -> Rename to something like: "Vul uw postcode en huisnummer in om uw adres te zoeken" 

But we disabled the plugin again, so not able to see if there are any other sentences which should be translated also.

**Comment by ZIPITRO** [comment]
> It would be a big improvement if there were translations (or at least a i18n dir and files) provided so it's easier to customize the extension and the frontend.
> Now everything is in English by default.

Would be indeed a big + to have all strings translated or to be able to use data-binding with ko.

**Comment by JozefVerhoef** [comment]
This has been improved in the latest release
