### ISSUE TITLE
Issue with overseas departments of France

### ISSUE THREAD

**Issue by Davie82** [postcode-nl/PostcodeNl_Api_Magento2#63]
In the backend of Magento it is possible to change the allowed countries for a website. These can be changed under Stores -> Configuration -> General -> General -> Country Options -> Allow Countries.

The list used for this config field also contains overseas departments of France like Guadeloupe, Martinique and Mayotte. Therefore it is normally possible to disallow shipping to one of these departments.

Unfortunately, even when the departments are not allowed, it is not working when using the PostcodeNL module. When I try to find an address for one of these departments the API will return a correct address and this is used for filling all the field inside the checkout.

## Expected result
- It is not possible to order from one of the overseas departments of France (when disabled in config)

## Actual result
- It is possible to order from one of these departments

**Comment by JerrySmidt** [comment]
Validation for the French overseas territories was added in release 3.1.9.
