### ISSUE TITLE
Conflict with OneStepCheckout module

### ISSUE THREAD

**Issue by marcoveeneman** [postcode-nl/PostcodeNl_Api_Magento2#65]
Hi,

I'm facing an issue when using both Postcode.eu and OneStepCheckout (from onestepcheckout.com) modules.

The checkout page is not loading, following lines can be found in the exception log:
`[2022-11-23 12:33:29] .CRITICAL: Notice: Undefined index: dataScopePrefix in <path>/vendor/postcode-nl/api-magento2-module/Block/Onepage/LayoutProcessor.php on line 79 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: dataScopePrefix in <path>/vendor/postcode-nl/api-magento2-module/Block/Onepage/LayoutProcessor.php on line 79 at <path>/vendor/magento/framework/App/ErrorHandler.php:61)"} null`

Looking in the module the following line in LayoutProcessor(79) is causing the exception:
`$billingForm['children']['form-fields']['children'] += $this->_updateCustomScope($autofillFields, $billingForm['dataScopePrefix']);`

After disabling this single line for testing, the following exception occurs:
`[2022-11-23 12:57:31] .CRITICAL: Notice: Undefined index: form-fields in <path>/vendor/postcode-nl/api-magento2-module/Block/Onepage/LayoutProcessor.php on line 80 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: form-fields in <path>/vendor/postcode-nl/api-magento2-module/Block/Onepage/LayoutProcessor.php on line 80 at <path>/vendor/magento/framework/App/ErrorHandler.php:61)"} null`

This is caused by this line in LayoutProcessor(80)
`$billingForm['children']['form-fields']['children'] = $this->_changeAddressFieldsPosition($billingForm['children']['form-fields']['children']);`

After disabling both lines 79 and 80 in the LayoutProcessor the checkout page is loading again. I'm trying to figure out if there is any harm in disabling these two lines, can someone say something about that?

**Comment by JerrySmidt** [comment]
Hi, yes disabling those lines could break form validation and prevents moving address fields in billing forms.

The dataScopePrefix is used with field validation, disabling it will likely cause issues with autocomplete field validation in the billing forms of your checkout.

The condition above (on line 74) checks for billing forms and if a form is found  it is assumed that the form has fields (`$billingForm['children']['form-fields']['children']`). But in this case the `form-fields` index also seems to be missing.

Does the issue persist when you disable the OneStepCheckout module? Just to be sure that it is a compatibility issue with this module. By looking at the component paths in their demo (http://m2.demo.onestepcheckout.com), it should be compatible. Although their demo is configured with "Display Billing Address On" -> "Payment Page" which uses different paths.

Let me know if you find out which entry in your billing configuration is causing this.

**Comment by marcoveeneman** [comment]
I took some more time to look a bit further into this and it seems that OSC itself is working fine.

I have another module installed, Amasty_CompanyAccount, that seems to be causing the problem in the checkout.

Following is the content of the `amasty_company_credit-form` which causes the problem in the LayoutProcessor of postcode-nl. As you can see the 'form-fields' do not exist here.

```json
"amasty_company_credit-form": {
  "children": {
    "cards": {
      "component": "uiComponent",
      "displayArea": "cards",
      "children": {
        "balance": {
          "component": "uiComponent",
          "config": {
            "template": "Amasty_CompanyAccount\/payment\/card\/balance"
          }
        },
        "be_paid": {
          "component": "uiComponent",
          "config": {
            "tooltips": {
              "tooltipTpl": "Amasty_CompanyAccount\/form\/component\/tooltip-container",
              "tooltipOne": {
                "description": "Calculated as {used_store_credit} minus {repayment_amount}, where:\n                                                                                                    {used_store_credit} is the sum of orders paid with store credit less refunded amounts,\n                                                                                                    {repayment_amount} is the sum of real money actually paid by Company to cover store credit usage."
              },
              "tooltipTwo": {
                "description": "The negative store credit balance has to be repaid until the stated date, otherwise the penalty will be applied every day to the whole overdraft amount."
              },
              "tooltipThree": {
                "description": "The penalty will be applied everyday on the overdraft amount until the Current Balance is positive or 0."
              }
            },
            "template": "Amasty_CompanyAccount\/payment\/card\/paid"
          }
        }
      }
    }
  }
}
```

If i add the following check to the LayoutProcessor, after the `if (!strpos($key, '-form')) {` check, the checkout seems to work again.

```php
if (!isset($billingForm['children']['form-fields'])) {
  continue;
}
```

For me this change would solve my problems. Is this something to add to the module by default?

**Comment by JerrySmidt** [comment]
Very nice. I'll add this change to the module.

Thanks for debugging.
