### ISSUE TITLE
Add manual entry link - Not working

### ISSUE THREAD

**Issue by JelleGe** [postcode-nl/PostcodeNl_Api_Magento2#68]
The function "Add manual entry link" does not work anymore with the latest version 3.1.9, even it is enabled in the backend settings.
This option is not shown in frontend.

**Comment by JerrySmidt** [comment]
The manual entry link only applies to the autocomplete field and not to the postcode + house number fields. And is shown when the autocomplete field has an error (e.g. on blur with incomplete address).

I've just compared versions 3.1.8 and 3.1.9 and the link behaves the same in both.

Is the link still missing if you have an error shown on the autocomplete field?

**Comment by JelleGe** [comment]
Sadly with the latest version the manual entry link is not shown, when the autocomplete has an error. When we fill in a wrong house number with postcode combination, the house number field shows an error with the message; the address could not be found. We come from 3.1.7.1 and it works well in that version.

**Comment by JerrySmidt** [comment]
This option only applies to the single autocomplete field. It was never implemented for the postcode + house number fields (same in 3.1.7.1).

See also https://github.com/JerrySmidt/PostcodeNl_Api_Magento2/issues/42

**Comment by JelleGe** [comment]
Hmm well it does works on 3.1.7.1 with the postcode + house number field. But will this be added also for postcode + house number fields in a future release?

**Comment by JerrySmidt** [comment]
Sure, perhaps we'll add this in the future.
