### ISSUE TITLE
Translations for nl_BE

### ISSUE THREAD

**Issue by JSeverein** [postcode-nl/PostcodeNl_Api_Magento2#69]
Hi,

Would it be possible to add the translations for Flemish (i18n/nl_BE.csv)?

**Comment by JerrySmidt** [comment]
Hello,

Yes, adding translations is pretty easy.  It only requires adding the CSV file you mentioned.

Just copy from nl_NL.csv and change text where needed.

If you like, you can add translations via pull request or drop a file here.

**Comment by Paulsky** [comment]
@JSeverein this has been fixed in #76

**Comment by JSeverein** [comment]
Thanks @Paulsky
