### ISSUE TITLE
JS error in browser console after clicking on adres line 1 input

### ISSUE THREAD

**Issue by gerben86** [postcode-nl/PostcodeNl_Api_Magento2#7]
When clicking on the AdresLine 1 there is a JavaScript error in the console: 
![image](https://user-images.githubusercontent.com/17478858/71599696-3bdbf080-2b4c-11ea-9822-cc9ef3bfe7fd.png)

**Comment by tmishutin** [comment]
@gerben86 it seems like you didn't clear / reset cache on your server or client side. If the issue is reproducible, please provide us with the URL.

**Comment by gerben86** [comment]
The issue was reproducable, not able to share an URL because we disabled it do the other finding about the addressline.

**Comment by JozefVerhoef** [comment]
Do you still experience this issue with release 2.0.0?

**Comment by gerben86** [comment]
We switched to another setup.
