### ISSUE TITLE
Address autocomplete on customer registration page

### ISSUE THREAD

**Issue by marcoveeneman** [postcode-nl/PostcodeNl_Api_Magento2#70]
Hi,

I would like new customers of a store to use the address autocomplete feature on the registration page (`mystore.com/customer/account/create/`) so that a customer can enter it's address more easily and also the address is already correct when the customer is registered.

The address fields on the customer registration page are enabled by setting the following in `customer_account_create.xml` layout file:
```xml
<referenceBlock name="customer_form_register">
    <arguments>
        <argument name="show_address_fields" xsi:type="boolean">true</argument>
    </arguments>
</referenceBlock>
```

The `show_address_fields` argument is used in the following template to render the address fields: `/vendor/magento/module-customer/view/frontend/templates/form/register.phtml`

**Question**: Is it possible to integrate the address autocomplete feature in this customer registration form?

**Comment by JerrySmidt** [comment]
Hello,

Yes, it should be possible to use address autocomplete there as well. It looks like it requires a similar implementation to the one used for the customer address fields in the address book. So you can use that as a reference if you are building your own.

These fields will also likely be supported in a future release of the module.

**Comment by marcoveeneman** [comment]
Hi Jerry,

Thanks for the info, i will give it a try myself as i cannot wait for a future version unfortunately.

While testing the address autocomplete on the customer address book i think i found a bug which causes the autocomplete module to not work. See #71

**Comment by JerrySmidt** [comment]
:ok:
