### ISSUE TITLE
Translation of validation message when an address is invalid

### ISSUE THREAD

**Issue by hd-jeroen** [postcode-nl/PostcodeNl_Api_Magento2#87]
When using the plugin on a Dutch webshop which the language set to Dutch (nl_NL) the "Address not found" string is not being translated to the Dutch language, even though the translate string is available in the nl_NL.csv file.

![image](https://github.com/postcode-nl/PostcodeNl_Api_Magento2/assets/80255844/bc81897b-db9e-431d-a224-962b65ceef4f)

**Comment by JerrySmidt** [comment]
Reasons for translations not being applied:

* Caching: after adding or modifying translations, always clear the cache.
* Compilation: in production mode, you might need to recompile after making changes to translations.
* Static Content Deployment: translations can also be part of the static content. After changing translations, you might need to redeploy static content.
* Locale Setting: ensure locale is set to `nl_NL`.
* Translation Priority: Translations in the theme will override translations in modules. Similarly, translations in the database (if any) will override those in the theme and modules.
* Translation Strategy: Magento has a "translation strategy" configuration that can be set to "merge" or "replace". If it's set to "replace", then only the theme's translations will be used, and module translations will be ignored.
* Other modules: can modify how translations are handled.

You could also check logs for any errors or warnings related to translations.

**Comment by JerrySmidt** [comment]
The translation should be there if you run `php bin/magento setup:static-content:deploy nl_NL` or if Magento is in developer mode. Not sure why the string isn't in your `js-translation.json` file. I'm not able to reproduce the issue here.
