### ISSUE TITLE
[Feature] Make disabled fields optional

### ISSUE THREAD

**Issue by Stevie-Ray** [postcode-nl/PostcodeNl_Api_Magento2#9]
Multiple clients requested us to have autocomplete but to not disable checkout fields. Not all adreses are found by the module especially new addresses can have some trouble. Allowing a custom to manually change there adres fixed this issue.

**Comment by tmishutin** [comment]
This will be implemented in the coming release in a few days.

**Comment by Stevie-Ray** [comment]
@tmishutin thanks! i was also wondering why changeAddressFieldPosition function is used to order the checkout fields instead of XML. Now we need to override the function to change the checkout order, instead of just updating `checkout_index_index.xml`
