### ISSUE TITLE
Hyvä Checkout support

### ISSUE THREAD

**Issue by Paulsky** [postcode-nl/PostcodeNl_Api_Magento2#96]
Hello, 

Is this extension compatible with the Hyvä Checkout extension?

**Comment by JerrySmidt** [comment]
Hi Paulsky,

No, this module is not compatible with Hyvä Checkout. But at least the following two modules are:

* https://gitlab.hyva.io/hyva-checkout/checkout-integrations/magento2-hyva-checkout-postcodenl
* https://github.com/trinos-nl/magento2-postcode-nl

**Comment by Paulsky** [comment]
Thank you!
